# -*- coding: utf-8 -*-
import os

BASE = r"d:\Datomate AI Lab\CalcWebsite"

def page(filename, title, desc, keywords, icon, g1, g2, cat, catIcon, catLbl, body, script=""):
    html = '<!DOCTYPE html>\n<html lang="en" data-theme="light">\n<head>\n<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">\n<title>' + title + ' | SuperCalc</title>\n<meta name="description" content="' + desc + '">\n<meta name="keywords" content="' + keywords + '">\n<link rel="canonical" href="https://supercalc.online/' + filename + '">\n<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&display=swap" rel="stylesheet">\n<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">\n<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">\n<link rel="stylesheet" href="css/style.css">\n</head>\n<body>\n<nav class="navbar navbar-expand-lg"><div class="container"><a class="navbar-brand" href="index.html">&#9889; Super<span>Calc</span></a><button class="navbar-toggler border-0" type="button" data-bs-toggle="collapse" data-bs-target="#nav"><span></span></button><div class="collapse navbar-collapse" id="nav"><ul class="navbar-nav me-auto ms-3"><li><a class="nav-link" href="index.html#' + cat + '">' + catIcon + ' ' + catLbl + '</a></li></ul><div class="d-flex gap-2"><button class="theme-toggle" id="themeToggle"><i class="bi bi-moon-fill" id="themeIcon"></i></button></div></div></div></nav>\n<div class="calc-page-header" style="background:linear-gradient(135deg,' + g1 + ',' + g2 + ')">\n  <div class="container"><nav class="breadcrumb-nav"><a href="index.html">Home</a> <i class="bi bi-chevron-right"></i><span>' + title + '</span></nav>\n  <h1 class="calc-page-title">' + icon + ' ' + title + '</h1>\n  <p class="calc-page-subtitle">' + desc + '</p></div>\n</div>\n<div class="container my-4">\n  <div class="row g-4">\n    <div class="col-lg-8">' + body + '</div>\n    <div class="col-lg-4"><div class="sidebar-ad"><span style="font-size:0.7rem;color:var(--text-muted)">Advertisement [300x250]</span></div></div>\n  </div>\n</div>\n<footer><div class="container"><div class="footer-bottom"><p>&copy; 2025 SuperCalc.online</p><div><a href="privacy.html">Privacy</a> &bull; <a href="terms.html">Terms</a></div></div></div></footer>\n<button class="back-to-top" id="backToTop"><i class="bi bi-arrow-up"></i></button>\n<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"></script>\n<script src="js/main.js"></script>\n' + script + '\n</body>\n</html>'
    with open(os.path.join(BASE, filename), 'w', encoding='utf-8') as f:
        f.write(html)
    print("Created: " + filename)

def cb(title, fields, res_list, btn="Calculate"):
    r = "".join(['<div class="col-6"><div class="result-label">' + r[0] + '</div><div class="result-value" id="' + r[1] + '">-</div></div>' for r in res_list])
    return '<div class="calc-box"><h2 class="calc-title">' + title + '</h2>' + fields + '<button class="btn-calculate mt-4" onclick="calc()"><i class="bi bi-calculator me-2"></i>' + btn + '</button><div class="result-box" id="resultBox"><div class="row g-3 text-center">' + r + '</div></div></div>'

calcs = [
("horsepower-calculator.html","Horsepower Calculator","Calculate engine horsepower from torque and RPM. Convert between HP, kW, and metric PS.","horsepower calculator, torque to horsepower, engine power calculator, HP to kW, watts to horsepower","&#128663;","#b71c1c","#c62828","tech","&#128187;","Tech & Dev",
cb("Horsepower Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Torque (lb-ft)</label><input type='number' class='form-control' id='f1' value='300' step='1'></div><div class='col-md-6'><label class='form-label'>RPM</label><input type='number' class='form-control' id='f2' value='4000' step='100'></div></div>",
[("Horsepower (HP)","r1"),("Kilowatts (kW)","r2"),("Metric PS","r3"),("Torque (Nm)","r4")],"Calculate HP"),
"<script>function calc(){const t=+document.getElementById('f1').value,r=+document.getElementById('f2').value;const hp=t*r/5252,kw=hp*0.7457,ps=hp*1.01387,nm=t*1.35582;document.getElementById('r1').textContent=hp.toFixed(2)+' HP';document.getElementById('r2').textContent=kw.toFixed(2)+' kW';document.getElementById('r3').textContent=ps.toFixed(2)+' PS';document.getElementById('r4').textContent=nm.toFixed(2)+' Nm';document.getElementById('resultBox').classList.add('show');}</script>"),

("tide-calculator.html","Tidal Volume Calculator","Calculate tidal volume and minute ventilation for mechanical ventilation based on patient weight.","tidal volume calculator, minute ventilation, ideal body weight, respiratory calculator, ventilator settings","&#127754;","#006064","#00838f","health","&#10084;","Health",
cb("Tidal Volume Calculator (Mechanical Ventilation)","<div class='row g-3'><div class='col-md-4'><label class='form-label'>Height (cm)</label><input type='number' class='form-control' id='f1' value='170' step='1'></div><div class='col-md-4'><label class='form-label'>Gender</label><select class='form-select' id='f2'><option value='m'>Male</option><option value='f'>Female</option></select></div><div class='col-md-4'><label class='form-label'>Respiratory Rate</label><input type='number' class='form-control' id='f3' value='14' step='1'></div></div>",
[("Ideal Body Weight","r1"),("Tidal Volume (6 ml/kg)","r2"),("Tidal Volume (8 ml/kg)","r3"),("Minute Ventilation","r4")],"Calculate"),
"<script>function calc(){const h=+document.getElementById('f1').value,g=document.getElementById('f2').value,rr=+document.getElementById('f3').value;const ibw=g==='m'?50+0.906*(h-152.4):45.5+0.906*(h-152.4);const tv6=ibw*6,tv8=ibw*8,mv=tv6*rr;document.getElementById('r1').textContent=ibw.toFixed(1)+' kg';document.getElementById('r2').textContent=tv6.toFixed(0)+' mL';document.getElementById('r3').textContent=tv8.toFixed(0)+' mL';document.getElementById('r4').textContent=(mv/1000).toFixed(2)+' L/min';document.getElementById('resultBox').classList.add('show');}</script>"),

("dose-calculator.html","Drug Dose Calculator","Calculate pediatric and adult medication dosages by weight. Essential for medical and nursing professionals.","drug dose calculator, medication dose calculator, mg per kg calculator, pediatric dosing, weight based dosing","&#128138;","#4a148c","#6a1b9a","health","&#10084;","Health",
cb("Weight-Based Dose Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Patient Weight (kg)</label><input type='number' class='form-control' id='f1' value='70' step='0.5'></div><div class='col-md-6'><label class='form-label'>Dose (mg/kg)</label><input type='number' class='form-control' id='f2' value='10' step='0.1'></div><div class='col-md-6'><label class='form-label'>Frequency (doses/day)</label><input type='number' class='form-control' id='f3' value='2' step='1'></div><div class='col-md-6'><label class='form-label'>Concentration (mg/mL)</label><input type='number' class='form-control' id='f4' value='50' step='1'></div></div>",
[("Single Dose (mg)","r1"),("Daily Total (mg)","r2"),("Volume Per Dose (mL)","r3"),("Weekly Total (mg)","r4")],"Calculate Dose"),
"<script>function calc(){const w=+document.getElementById('f1').value,d=+document.getElementById('f2').value,f=+document.getElementById('f3').value,c=+document.getElementById('f4').value;const single=w*d,daily=single*f,vol=single/c;document.getElementById('r1').textContent=single.toFixed(2)+' mg';document.getElementById('r2').textContent=daily.toFixed(2)+' mg';document.getElementById('r3').textContent=vol.toFixed(2)+' mL';document.getElementById('r4').textContent=(daily*7).toFixed(2)+' mg';document.getElementById('resultBox').classList.add('show');}</script>"),

("depreciation-calculator.html","Depreciation Calculator","Calculate straight-line, declining balance, and sum-of-years digits depreciation for any asset.","depreciation calculator, asset depreciation, straight line depreciation, double declining balance, tax depreciation","&#128200;","#37474f","#455a64","finance","&#128176;","Finance",
cb("Asset Depreciation Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Asset Cost ($)</label><input type='number' class='form-control' id='f1' value='50000' step='1000'></div><div class='col-md-6'><label class='form-label'>Salvage Value ($)</label><input type='number' class='form-control' id='f2' value='5000' step='500'></div><div class='col-md-6'><label class='form-label'>Useful Life (years)</label><input type='number' class='form-control' id='f3' value='5' step='1'></div><div class='col-md-6'><label class='form-label'>Year to Calculate</label><input type='number' class='form-control' id='f4' value='1' min='1' step='1'></div></div>",
[("Straight-Line Dep./yr","r1"),("Declining Balance Dep.","r2"),("Book Value (SL)","r3"),("Accumulated Dep. (SL)","r4")],"Calculate Depreciation"),
"<script>function calc(){const cost=+document.getElementById('f1').value,sv=+document.getElementById('f2').value,life=+document.getElementById('f3').value,yr=+document.getElementById('f4').value;const sl=(cost-sv)/life,db=(cost-sv)*(2/life)*Math.pow(1-2/life,yr-1),bookSL=cost-sl*yr,accumSL=sl*yr;document.getElementById('r1').textContent='$'+sl.toFixed(2);document.getElementById('r2').textContent='$'+db.toFixed(2)+' (yr '+yr+')';document.getElementById('r3').textContent='$'+bookSL.toFixed(2);document.getElementById('r4').textContent='$'+accumSL.toFixed(2);document.getElementById('resultBox').classList.add('show');}</script>"),

("bond-yield-calculator.html","Bond Yield Calculator","Calculate bond yield to maturity (YTM), current yield, and bond price for fixed income investments.","bond yield calculator, yield to maturity, bond price calculator, coupon rate, fixed income, YTM calculator","&#128185;","#1b5e20","#2e7d32","finance","&#128176;","Finance",
cb("Bond Yield Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Face Value ($)</label><input type='number' class='form-control' id='f1' value='1000' step='100'></div><div class='col-md-6'><label class='form-label'>Current Price ($)</label><input type='number' class='form-control' id='f2' value='950' step='10'></div><div class='col-md-6'><label class='form-label'>Coupon Rate (%)</label><input type='number' class='form-control' id='f3' value='5' step='0.1'></div><div class='col-md-6'><label class='form-label'>Years to Maturity</label><input type='number' class='form-control' id='f4' value='10' step='1'></div></div>",
[("Annual Coupon ($)","r1"),("Current Yield","r2"),("Approx YTM","r3"),("Total Return","r4")],"Calculate Yield"),
"<script>function calc(){const fv=+document.getElementById('f1').value,price=+document.getElementById('f2').value,cr=+document.getElementById('f3').value/100,n=+document.getElementById('f4').value;const coupon=fv*cr,cy=coupon/price*100,ytm=((coupon+(fv-price)/n)/((fv+price)/2))*100,total=coupon*n+(fv-price);document.getElementById('r1').textContent='$'+coupon.toFixed(2);document.getElementById('r2').textContent=cy.toFixed(3)+'%';document.getElementById('r3').textContent=ytm.toFixed(3)+'%';document.getElementById('r4').textContent='$'+total.toFixed(2);document.getElementById('resultBox').classList.add('show');}</script>"),

("options-profit-calculator.html","Options P&L Calculator","Calculate profit and loss for call and put options at various stock prices at expiration.","options calculator, call option profit, put option calculator, options P&L, options trading, breakeven option","&#128200;","#0d47a1","#1565c0","finance","&#128176;","Finance",
cb("Options P&L Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Option Type</label><select class='form-select' id='f0'><option value='call'>Call Option</option><option value='put'>Put Option</option></select></div><div class='col-md-6'><label class='form-label'>Strike Price ($)</label><input type='number' class='form-control' id='f1' value='100' step='1'></div><div class='col-md-6'><label class='form-label'>Premium Paid ($)</label><input type='number' class='form-control' id='f2' value='5' step='0.5'></div><div class='col-md-6'><label class='form-label'>Stock Price at Expiry ($)</label><input type='number' class='form-control' id='f3' value='110' step='1'></div><div class='col-md-6'><label class='form-label'>Number of Contracts</label><input type='number' class='form-control' id='f4' value='1' step='1'></div></div>",
[("Profit/Loss Per Share","r1"),("Total P&L","r2"),("Break-Even Price","r3"),("Return on Investment","r4")],"Calculate P&L"),
"<script>function calc(){const type=document.getElementById('f0').value,K=+document.getElementById('f1').value,prem=+document.getElementById('f2').value,S=+document.getElementById('f3').value,n=+document.getElementById('f4').value;let intrinsic,pl;if(type==='call'){intrinsic=Math.max(0,S-K);pl=intrinsic-prem;}else{intrinsic=Math.max(0,K-S);pl=intrinsic-prem;}const total=pl*100*n,be=type==='call'?K+prem:K-prem,roi=prem>0?pl/prem*100:0;document.getElementById('r1').textContent=(pl>=0?'+$':'$')+pl.toFixed(2);document.getElementById('r2').textContent=(total>=0?'+$':'$')+total.toFixed(2);document.getElementById('r3').textContent='$'+be.toFixed(2);document.getElementById('r4').textContent=roi.toFixed(1)+'%';document.getElementById('resultBox').classList.add('show');}</script>"),

("swimming-calorie-calculator.html","Swimming Calorie Calculator","Calculate calories burned swimming by stroke type, distance, and body weight. Compare swimming vs running.","swimming calorie calculator, calories burned swimming, swim workout calorie, swimming MET, pool workout calories","&#127946;","#006064","#00838f","health","&#10084;","Health",
cb("Swimming Calorie Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Body Weight (kg)</label><input type='number' class='form-control' id='f1' value='70' step='0.5'></div><div class='col-md-6'><label class='form-label'>Swim Stroke</label><select class='form-select' id='f2'><option value='7.0'>Freestyle (moderate)</option><option value='9.8'>Freestyle (fast)</option><option value='7.0'>Backstroke</option><option value='10.3'>Breaststroke</option><option value='13.8'>Butterfly</option><option value='6.0'>Water polo</option></select></div><div class='col-md-6'><label class='form-label'>Duration (minutes)</label><input type='number' class='form-control' id='f3' value='30' step='5'></div></div>",
[("Calories Burned","r1"),("Per Minute","r2"),("Equal to Running","r3"),("MET Value","r4")],"Calculate"),
"<script>function calc(){const w=+document.getElementById('f1').value,met=+document.getElementById('f2').value,min=+document.getElementById('f3').value;const cal=met*w*3.5*min/(200),perMin=cal/min,runMins=cal/8.5;document.getElementById('r1').textContent=cal.toFixed(0)+' kcal';document.getElementById('r2').textContent=perMin.toFixed(1)+' kcal/min';document.getElementById('r3').textContent=runMins.toFixed(0)+' min running';document.getElementById('r4').textContent=met;document.getElementById('resultBox').classList.add('show');}</script>"),

("cycling-calorie-calculator.html","Cycling Calorie Calculator","Calculate calories burned cycling by speed, duration, terrain, and body weight. Supports indoor and outdoor cycling.","cycling calorie calculator, bike calories burned, cycling workout, bicycle calorie calculator, indoor cycling calories","&#128690;","#1b5e20","#2e7d32","health","&#10084;","Health",
cb("Cycling Calorie Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Body Weight (kg)</label><input type='number' class='form-control' id='f1' value='75' step='0.5'></div><div class='col-md-6'><label class='form-label'>Cycling Intensity</label><select class='form-select' id='f2'><option value='4.0'>Leisurely (&lt;16 km/h)</option><option value='6.8'>Moderate (16-19 km/h)</option><option value='8.0' selected>Vigorous (19-22 km/h)</option><option value='10.0'>Racing (&gt;22 km/h)</option><option value='5.5'>Stationary Bike</option></select></div><div class='col-md-6'><label class='form-label'>Duration (minutes)</label><input type='number' class='form-control' id='f3' value='45' step='5'></div></div>",
[("Calories Burned","r1"),("Distance (est.)","r2"),("Calories/km","r3"),("Weekly Total (5x)","r4")],"Calculate"),
"<script>function calc(){const w=+document.getElementById('f1').value,met=+document.getElementById('f2').value,min=+document.getElementById('f3').value;const cal=met*w*3.5*min/200,speeds={4:14,6.8:17.5,8:20.5,10:25,5.5:0};const dist=(met*min/60*5);document.getElementById('r1').textContent=cal.toFixed(0)+' kcal';document.getElementById('r2').textContent=dist.toFixed(1)+' km (est.)';document.getElementById('r3').textContent=(cal/Math.max(dist,0.1)).toFixed(1)+' kcal/km';document.getElementById('r4').textContent=(cal*5).toFixed(0)+' kcal';document.getElementById('resultBox').classList.add('show');}</script>"),

("yoga-calorie-calculator.html","Yoga Calorie Calculator","Calculate calories burned doing yoga by style and duration. Compare hot yoga, vinyasa, and restorative yoga.","yoga calorie calculator, calories burned yoga, hot yoga calories, vinyasa calories, yoga workout calculator","&#129340;","#880e4f","#ad1457","health","&#10084;","Health",
cb("Yoga Calorie Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Body Weight (kg)</label><input type='number' class='form-control' id='f1' value='65' step='0.5'></div><div class='col-md-6'><label class='form-label'>Yoga Style</label><select class='form-select' id='f2'><option value='2.5'>Hatha (gentle)</option><option value='3.3'>Vinyasa flow</option><option value='4.5'>Power yoga</option><option value='5.0'>Hot yoga (Bikram)</option><option value='2.0'>Restorative</option><option value='3.8'>Ashtanga</option></select></div><div class='col-md-6'><label class='form-label'>Duration (minutes)</label><input type='number' class='form-control' id='f3' value='60' step='15'></div></div>",
[("Calories Burned","r1"),("Per Minute","r2"),("Per Hour","r3"),("Weekly (4 sessions)","r4")],"Calculate"),
"<script>function calc(){const w=+document.getElementById('f1').value,met=+document.getElementById('f2').value,min=+document.getElementById('f3').value;const cal=met*w*3.5*min/200;document.getElementById('r1').textContent=cal.toFixed(0)+' kcal';document.getElementById('r2').textContent=(cal/min).toFixed(1)+' kcal/min';document.getElementById('r3').textContent=(cal*60/min).toFixed(0)+' kcal';document.getElementById('r4').textContent=(cal*4).toFixed(0)+' kcal/week';document.getElementById('resultBox').classList.add('show');}</script>"),

("walking-calorie-calculator.html","Walking Calorie Calculator","Calculate calories burned walking by speed, distance, weight, and terrain. Compare walking to other exercises.","walking calorie calculator, calories burned walking, steps to calories, walking weight loss, walk exercise calories","&#128694;","#4a148c","#6a1b9a","health","&#10084;","Health",
cb("Walking Calorie Calculator","<div class='row g-3'><div class='col-md-4'><label class='form-label'>Weight (kg)</label><input type='number' class='form-control' id='f1' value='70' step='0.5'></div><div class='col-md-4'><label class='form-label'>Distance (km)</label><input type='number' class='form-control' id='f2' value='5' step='0.5'></div><div class='col-md-4'><label class='form-label'>Speed</label><select class='form-select' id='f3'><option value='2.5'>Slow (3 km/h)</option><option value='3.5' selected>Moderate (5 km/h)</option><option value='4.3'>Brisk (6 km/h)</option><option value='5.0'>Fast (7 km/h)</option></select></div></div>",
[("Calories Burned","r1"),("Duration","r2"),("Steps (est.)","r3"),("Per km","r4")],"Calculate"),
"<script>function calc(){const w=+document.getElementById('f1').value,d=+document.getElementById('f2').value,met=+document.getElementById('f3').value;const speed=met===2.5?3:met===3.5?5:met===4.3?6:7,mins=d/speed*60,cal=met*w*3.5*mins/200,steps=d*1312;document.getElementById('r1').textContent=cal.toFixed(0)+' kcal';document.getElementById('r2').textContent=mins.toFixed(0)+' min';document.getElementById('r3').textContent=Math.round(steps).toLocaleString()+' steps';document.getElementById('r4').textContent=(cal/d).toFixed(0)+' kcal';document.getElementById('resultBox').classList.add('show');}</script>"),

("concrete-calculator.html","Concrete Mix Calculator","Calculate concrete mix ratios for cement, sand, and aggregate. Find number of cement bags needed.","concrete mix calculator, cement sand aggregate ratio, concrete bags calculator, M10 M20 mix, concrete volume","&#127959;","#616161","#757575","construction","&#127959;","Construction",
cb("Concrete Mix Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Volume of Concrete (m&#179;)</label><input type='number' class='form-control' id='f1' value='1' step='0.1'></div><div class='col-md-6'><label class='form-label'>Mix Grade</label><select class='form-select' id='f2'><option value='1,3,6'>M10 (1:3:6)</option><option value='1,2,4' selected>M15 (1:2:4)</option><option value='1,1.5,3'>M20 (1:1.5:3)</option><option value='1,1,2'>M25 (1:1:2)</option></select></div><div class='col-md-6'><label class='form-label'>Cement Bag Size (kg)</label><select class='form-select' id='f3'><option value='50' selected>50 kg</option><option value='40'>40 kg</option></select></div></div>",
[("Cement Bags","r1"),("Sand (m&#179;)","r2"),("Aggregate (m&#179;)","r3"),("Water-Cement Ratio","r4")],"Calculate Mix"),
"<script>function calc(){const vol=+document.getElementById('f1').value,mix=document.getElementById('f2').value.split(',').map(Number),bagKg=+document.getElementById('f3').value;const total=mix.reduce(function(a,b){return a+b;},0),dryVol=vol*1.54,cement=dryVol*(mix[0]/total)*1440,bags=Math.ceil(cement/bagKg),sand=dryVol*(mix[1]/total),agg=dryVol*(mix[2]/total);document.getElementById('r1').textContent=bags+' bags ('+cement.toFixed(0)+'kg)';document.getElementById('r2').textContent=sand.toFixed(3)+' m\u00B3';document.getElementById('r3').textContent=agg.toFixed(3)+' m\u00B3';document.getElementById('r4').textContent='0.45-0.55';document.getElementById('resultBox').classList.add('show');}</script>"),

("paint-coverage-calculator.html","Paint Coverage Calculator","Calculate how many liters or gallons of paint you need for any room or surface area. Includes primer estimation.","paint calculator, how much paint do I need, paint coverage, liters of paint, gallons of paint, wall paint calculator","&#127912;","#880e4f","#ad1457","construction","&#127959;","Construction",
cb("Paint Coverage Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Wall Area (sq ft)</label><input type='number' class='form-control' id='f1' value='500' step='10'></div><div class='col-md-6'><label class='form-label'>Number of Coats</label><select class='form-select' id='f2'><option value='1'>1 coat</option><option value='2' selected>2 coats</option><option value='3'>3 coats</option></select></div><div class='col-md-6'><label class='form-label'>Paint Coverage (sq ft/gal)</label><input type='number' class='form-control' id='f3' value='350' step='10'></div><div class='col-md-6'><label class='form-label'>Paint Cost Per Gallon ($)</label><input type='number' class='form-control' id='f4' value='35' step='5'></div></div>",
[("Gallons Needed","r1"),("Liters Needed","r2"),("Total Paint Cost","r3"),("Area Per Liter","r4")],"Calculate Paint"),
"<script>function calc(){const area=+document.getElementById('f1').value,coats=+document.getElementById('f2').value,cov=+document.getElementById('f3').value,price=+document.getElementById('f4').value;const gals=Math.ceil(area*coats/cov),liters=gals*3.785,cost=gals*price;document.getElementById('r1').textContent=gals+' gallons';document.getElementById('r2').textContent=liters.toFixed(1)+' liters';document.getElementById('r3').textContent='$'+cost.toFixed(0);document.getElementById('r4').textContent=(cov/3.785).toFixed(0)+' sq ft/L';document.getElementById('resultBox').classList.add('show');}</script>"),

("birth-year-calculator.html","Birth Year Calculator","Calculate birth year from age, or current age from birth year. Determine zodiac sign and generation.","birth year calculator, calculate age from birth year, what year was I born, age calculator by year, generation calculator","&#127874;","#4a148c","#6a1b9a","lifestyle","&#127774;","Lifestyle",
cb("Birth Year & Age Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Calculation Mode</label><select class='form-select' id='f0'><option value='age'>Age to Birth Year</option><option value='year'>Birth Year to Age</option></select></div><div class='col-md-6'><label class='form-label' id='inLbl'>Your Current Age</label><input type='number' class='form-control' id='f1' value='30' step='1'></div></div>",
[("Birth Year","r1"),("Current Age","r2"),("Generation","r3"),("Years to 100","r4")],"Calculate"),
"<script>document.getElementById('f0').onchange=function(){document.getElementById('inLbl').textContent=this.value==='age'?'Your Current Age':'Birth Year';};const gens=[[2013,'Gen Alpha'],[1997,'Gen Z'],[1981,'Millennial'],[1965,'Gen X'],[1946,'Baby Boomer'],[1928,'Silent Generation'],[0,'Greatest Generation']];function calc(){const mode=document.getElementById('f0').value,v=+document.getElementById('f1').value,yr=new Date().getFullYear();let by,age;if(mode==='age'){age=v;by=yr-v;}else{by=v;age=yr-v;}const gen=gens.find(function(g){return by>=g[0];})||gens[gens.length-1];document.getElementById('r1').textContent=by;document.getElementById('r2').textContent=age+' years';document.getElementById('r3').textContent=gen[1];document.getElementById('r4').textContent=(100-age)+' years';document.getElementById('resultBox').classList.add('show');}</script>"),

("anniversary-calculator.html","Anniversary Calculator","Calculate days until your anniversary, wedding anniversary name, and total days together as a couple.","anniversary calculator, wedding anniversary calculator, how many days together, anniversary countdown, couple days","&#128149;","#880e4f","#ad1457","lifestyle","&#127774;","Lifestyle",
cb("Anniversary Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Special Date</label><input type='date' class='form-control' id='f1'></div><div class='col-md-6'><label class='form-label'>Anniversary Type</label><select class='form-select' id='f2'><option value='wedding'>Wedding</option><option value='relationship'>Relationship</option><option value='custom'>Custom</option></select></div></div>",
[("Days Together","r1"),("Years Together","r2"),("Next Anniversary In","r3"),("Anniversary Name","r4")],"Calculate"),
"<script>const annivNames=['','Paper','Cotton','Leather','Fruit/Flowers','Wood','Candy/Iron','Wool/Copper','Pottery/Bronze','Pottery/Willow','Tin/Aluminum','','','Lace','Ivory','Crystal','','','','','China','','','Silver','','','','','','','Pearl','','','','','Coral','','','','','Ruby','','','','','Sapphire','','','','','Gold','','','','','Emerald','','','','','Diamond'];document.getElementById('f1').valueAsDate=new Date(new Date()-365*5*86400000);function calc(){const d=new Date(document.getElementById('f1').value),now=new Date(),days=Math.floor((now-d)/86400000),yrs=Math.floor(days/365);const nextAnniv=new Date(d);nextAnniv.setFullYear(now.getFullYear());if(nextAnniv<now)nextAnniv.setFullYear(now.getFullYear()+1);const rem=Math.ceil((nextAnniv-now)/86400000);const name=annivNames[yrs]||yrs+'th Anniversary';document.getElementById('r1').textContent=days.toLocaleString()+' days';document.getElementById('r2').textContent=yrs+' years';document.getElementById('r3').textContent=rem+' days';document.getElementById('r4').textContent=name;document.getElementById('resultBox').classList.add('show');}</script>"),

("countdown-calculator.html","Countdown Timer Calculator","Calculate exact time remaining until any future date or event. Days, hours, minutes, and seconds countdown.","countdown calculator, days until calculator, time remaining calculator, event countdown, deadline calculator","&#9200;","#0d47a1","#1565c0","datetime","&#128337;","Date & Time",
"""<div class='calc-box'><h2 class='calc-title'>Countdown Calculator</h2><div class='row g-3'><div class='col-md-6'><label class='form-label'>Event Name</label><input type='text' class='form-control' id='evName' value='New Year 2026' placeholder='Event name'></div><div class='col-md-6'><label class='form-label'>Event Date &amp; Time</label><input type='datetime-local' class='form-control' id='evDate'></div></div><button class='btn-calculate mt-4' onclick='calc()'><i class='bi bi-stopwatch me-2'></i>Calculate Countdown</button><div class='result-box' id='resultBox'><div class='row g-3 text-center'><div class='col-6'><div class='result-label'>Days</div><div class='result-value' id='r1'>-</div></div><div class='col-6'><div class='result-label'>Hours</div><div class='result-value' id='r2'>-</div></div><div class='col-6'><div class='result-label'>Minutes</div><div class='result-value' id='r3'>-</div></div><div class='col-6'><div class='result-label'>Total Hours</div><div class='result-value' id='r4'>-</div></div></div></div></div>""",
"<script>const ny=new Date();ny.setFullYear(ny.getFullYear()+1);ny.setMonth(0);ny.setDate(1);ny.setHours(0,0,0);document.getElementById('evDate').value=ny.toISOString().slice(0,16);function calc(){const ev=new Date(document.getElementById('evDate').value),now=new Date(),ms=ev-now;if(ms<0){document.getElementById('r1').textContent='Event passed';return;}const days=Math.floor(ms/86400000),hrs=Math.floor((ms%86400000)/3600000),mins=Math.floor((ms%3600000)/60000),totalH=Math.floor(ms/3600000);document.getElementById('r1').textContent=days.toLocaleString();document.getElementById('r2').textContent=hrs;document.getElementById('r3').textContent=mins;document.getElementById('r4').textContent=totalH.toLocaleString();document.getElementById('resultBox').classList.add('show');}</script>"),

("week-number-calculator.html","Week Number Calculator","Find the ISO week number for any date. Calculate which week of the year a date falls on.","week number calculator, what week is it, ISO week number, day of year calculator, week of year","&#128197;","#1b5e20","#2e7d32","datetime","&#128337;","Date & Time",
cb("Week Number Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Date</label><input type='date' class='form-control' id='f1'></div></div>",
[("Week Number","r1"),("Day of Year","r2"),("Quarter","r3"),("Days Until Year End","r4")],"Calculate"),
"<script>document.getElementById('f1').valueAsDate=new Date();function calc(){const d=new Date(document.getElementById('f1').value);const jan1=new Date(d.getFullYear(),0,1);const dayOfYear=Math.ceil((d-jan1)/86400000)+1;const weekNum=Math.ceil(dayOfYear/7);const q=Math.ceil((d.getMonth()+1)/3);const dec31=new Date(d.getFullYear(),11,31);const rem=Math.ceil((dec31-d)/86400000);document.getElementById('r1').textContent='Week '+weekNum+' of '+d.getFullYear();document.getElementById('r2').textContent='Day '+dayOfYear;document.getElementById('r3').textContent='Q'+q;document.getElementById('r4').textContent=rem+' days';document.getElementById('resultBox').classList.add('show');}</script>"),

("tip-calculator-uk.html","UK VAT Calculator","Calculate UK VAT (Value Added Tax) at 20%, 5%, or 0%. Add or remove VAT from any price instantly.","UK VAT calculator, value added tax calculator, VAT 20%, remove VAT, add VAT, British tax calculator","&#127468;&#127463;","#1a237e","#283593","finance","&#128176;","Finance",
"""<div class='calc-box'><h2 class='calc-title'>UK VAT Calculator</h2><div class='d-flex gap-2 mb-3 flex-wrap'><button class='cat-pill active' onclick='setMode(true,this)'>Add VAT</button><button class='cat-pill' onclick='setMode(false,this)'>Remove VAT</button></div><div class='row g-3'><div class='col-md-6'><label class='form-label' id='pl'>Amount (ex. VAT)</label><input type='number' class='form-control' id='f1' value='100' step='0.01'></div><div class='col-md-6'><label class='form-label'>VAT Rate</label><select class='form-select' id='f2'><option value='0.20' selected>Standard 20%</option><option value='0.05'>Reduced 5%</option><option value='0'>Zero Rated 0%</option></select></div></div><button class='btn-calculate mt-4' onclick='calc()'><i class='bi bi-calculator me-2'></i>Calculate VAT</button><div class='result-box' id='resultBox'><div class='row g-3 text-center'><div class='col-6'><div class='result-label'>Net Amount</div><div class='result-value' id='r1'>-</div></div><div class='col-6'><div class='result-label'>VAT Amount</div><div class='result-value' id='r2'>-</div></div><div class='col-6'><div class='result-label'>Gross Amount</div><div class='result-value' id='r3'>-</div></div><div class='col-6'><div class='result-label'>VAT Rate</div><div class='result-value' id='r4'>-</div></div></div></div></div>""",
"<script>let addVat=true;function setMode(m,b){addVat=m;document.querySelectorAll('.cat-pill').forEach(function(p){p.classList.remove('active');});b.classList.add('active');document.getElementById('pl').textContent=m?'Amount (ex. VAT)':'Amount (inc. VAT)';}function calc(){const v=+document.getElementById('f1').value,rate=+document.getElementById('f2').value;let net,vat,gross;if(addVat){net=v;vat=v*rate;gross=v+vat;}else{gross=v;net=v/(1+rate);vat=gross-net;}document.getElementById('r1').textContent='&#163;'+net.toFixed(2);document.getElementById('r2').textContent='&#163;'+vat.toFixed(2);document.getElementById('r3').textContent='&#163;'+gross.toFixed(2);document.getElementById('r4').textContent=(rate*100)+'%';document.getElementById('resultBox').classList.add('show');}</script>"),

("gst-india-calculator.html","India GST Calculator 2025","Calculate GST for goods and services in India. Supports all current GST slabs with CGST, SGST, and IGST breakdown.","GST calculator India, CGST SGST calculator, Indian GST slabs 2025, GST amount calculator, goods services tax India","&#127470;&#127475;","#ff8f00","#ff6f00","finance","&#128176;","Finance",
"""<div class='calc-box'><h2 class='calc-title'>India GST Calculator 2025</h2><div class='row g-3'><div class='col-md-6'><label class='form-label'>Amount</label><input type='number' class='form-control' id='f1' value='1000' step='1'></div><div class='col-md-6'><label class='form-label'>GST Rate</label><select class='form-select' id='f2'><option value='0'>0% (Exempted)</option><option value='3'>3% (Gold/Silver)</option><option value='5'>5% (Essential goods)</option><option value='12'>12% (Standard)</option><option value='18' selected>18% (Standard)</option><option value='28'>28% (Luxury)</option></select></div><div class='col-md-6'><label class='form-label'>Transaction Type</label><select class='form-select' id='f3'><option value='intra'>Intra-State (CGST+SGST)</option><option value='inter'>Inter-State (IGST)</option></select></div><div class='col-md-6'><label class='form-label'>Calculate</label><select class='form-select' id='f4'><option value='ex'>Amount excludes GST</option><option value='in'>Amount includes GST</option></select></div></div><button class='btn-calculate mt-4' onclick='calc()'><i class='bi bi-calculator me-2'></i>Calculate GST</button><div class='result-box' id='resultBox'><div class='row g-3 text-center'><div class='col-6'><div class='result-label'>Pre-GST Amount</div><div class='result-value' id='r1'>-</div></div><div class='col-6'><div class='result-label'>GST Amount</div><div class='result-value' id='r2'>-</div></div><div class='col-6'><div class='result-label' id='rl3'>CGST</div><div class='result-value' id='r3'>-</div></div><div class='col-6'><div class='result-label' id='rl4'>SGST</div><div class='result-value' id='r4'>-</div></div><div class='col-12'><div class='result-label'>Total Amount (with GST)</div><div class='result-value' id='r5' style='font-size:2rem;color:var(--primary)'>-</div></div></div></div></div>""",
"<script>function calc(){const amt=+document.getElementById('f1').value,rate=+document.getElementById('f2').value/100,type=document.getElementById('f3').value,mode=document.getElementById('f4').value;let pre,gst,total;if(mode==='ex'){pre=amt;gst=amt*rate;total=amt+gst;}else{total=amt;pre=amt/(1+rate);gst=total-pre;}if(type==='intra'){const half=gst/2;document.getElementById('rl3').textContent='CGST ('+rate*50+'%)';document.getElementById('rl4').textContent='SGST ('+rate*50+'%)';document.getElementById('r3').textContent='&#8377;'+half.toFixed(2);document.getElementById('r4').textContent='&#8377;'+half.toFixed(2);}else{document.getElementById('rl3').textContent='IGST ('+rate*100+'%)';document.getElementById('rl4').textContent='';document.getElementById('r3').textContent='&#8377;'+gst.toFixed(2);document.getElementById('r4').textContent='-';}document.getElementById('r1').textContent='&#8377;'+pre.toFixed(2);document.getElementById('r2').textContent='&#8377;'+gst.toFixed(2);document.getElementById('r5').textContent='&#8377;'+total.toFixed(2);document.getElementById('resultBox').classList.add('show');}</script>"),

("loan-emi-calculator.html","EMI Calculator - All Loan Types","Calculate EMI for home loan, personal loan, car loan, education loan with amortization schedule.","EMI calculator, loan EMI calculator, home loan EMI, personal loan EMI, car loan EMI, education loan EMI","&#127968;","#1a237e","#283593","finance","&#128176;","Finance",
cb("Loan EMI Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Loan Amount ($)</label><input type='number' class='form-control' id='f1' value='500000' step='10000'></div><div class='col-md-6'><label class='form-label'>Annual Interest Rate (%)</label><input type='number' class='form-control' id='f2' value='8.5' step='0.1'></div><div class='col-md-6'><label class='form-label'>Loan Tenure (years)</label><input type='number' class='form-control' id='f3' value='20' step='1'></div><div class='col-md-6'><label class='form-label'>Processing Fee (%)</label><input type='number' class='form-control' id='f4' value='1' step='0.1'></div></div>",
[("Monthly EMI","r1"),("Total Interest","r2"),("Total Amount Paid","r3"),("Processing Fee","r4")],"Calculate EMI"),
"<script>function calc(){const P=+document.getElementById('f1').value,r=+document.getElementById('f2').value/100/12,n=+document.getElementById('f3').value*12,fee=+document.getElementById('f4').value/100;const emi=P*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1),total=emi*n,int=total-P,feeAmt=P*fee;document.getElementById('r1').textContent='$'+emi.toFixed(2);document.getElementById('r2').textContent='$'+int.toFixed(0);document.getElementById('r3').textContent='$'+total.toFixed(0);document.getElementById('r4').textContent='$'+feeAmt.toFixed(0);document.getElementById('resultBox').classList.add('show');}</script>"),

("childbirth-cost-calculator.html","Childbirth Cost Calculator","Estimate total cost of having a baby including hospital, prenatal care, and baby essentials.","childbirth cost calculator, hospital birth cost, baby cost calculator, pregnancy expenses, newborn costs","&#128118;","#880e4f","#ad1457","health","&#10084;","Health",
cb("Childbirth Cost Estimator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Hospital Delivery Type</label><select class='form-select' id='f1'><option value='4000'>Vaginal birth - no complications</option><option value='6000' selected>C-section delivery</option><option value='2000'>Birth center</option><option value='500'>Home birth</option></select></div><div class='col-md-6'><label class='form-label'>Insurance Coverage (%)</label><input type='number' class='form-control' id='f2' value='80' step='5'></div><div class='col-md-6'><label class='form-label'>Prenatal Visits (est. $150 each)</label><input type='number' class='form-control' id='f3' value='15' step='1'></div><div class='col-md-6'><label class='form-label'>Baby Essentials Budget ($)</label><input type='number' class='form-control' id='f4' value='3000' step='500'></div></div>",
[("Total Delivery Cost","r1"),("Your Out-of-Pocket","r2"),("Prenatal Care","r3"),("First Year Total","r4")],"Estimate Cost"),
"<script>function calc(){const del=+document.getElementById('f1').value,ins=+document.getElementById('f2').value/100,visits=+document.getElementById('f3').value,baby=+document.getElementById('f4').value;const prenatal=visits*150,oop=del*(1-ins),firstYear=oop+prenatal+baby+12000;document.getElementById('r1').textContent='$'+del.toFixed(0);document.getElementById('r2').textContent='$'+oop.toFixed(0);document.getElementById('r3').textContent='$'+prenatal.toFixed(0);document.getElementById('r4').textContent='$'+firstYear.toFixed(0)+' (est.)';document.getElementById('resultBox').classList.add('show');}</script>"),

("college-cost-calculator.html","College Cost Calculator","Estimate total college education cost including tuition, room & board, books, and living expenses.","college cost calculator, university tuition calculator, cost of college, student loan calculator, education cost","&#127979;","#0d47a1","#1565c0","education","&#127979;","Education",
cb("College Cost Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Annual Tuition ($)</label><input type='number' class='form-control' id='f1' value='30000' step='1000'></div><div class='col-md-6'><label class='form-label'>Room &amp; Board ($/year)</label><input type='number' class='form-control' id='f2' value='12000' step='500'></div><div class='col-md-6'><label class='form-label'>Books &amp; Supplies ($/year)</label><input type='number' class='form-control' id='f3' value='1500' step='100'></div><div class='col-md-6'><label class='form-label'>Personal Expenses ($/year)</label><input type='number' class='form-control' id='f4' value='3000' step='100'></div><div class='col-md-6'><label class='form-label'>Years in College</label><input type='number' class='form-control' id='f5' value='4' step='1'></div><div class='col-md-6'><label class='form-label'>Annual Cost Increase (%)</label><input type='number' class='form-control' id='f6' value='5' step='0.5'></div></div>",
[("Total Education Cost","r1"),("Year 1 Cost","r2"),("Year 4 Cost","r3"),("Monthly Loan Payment","r4")],"Calculate Cost"),
"<script>function calc(){const t=+document.getElementById('f1').value,r=+document.getElementById('f2').value,b=+document.getElementById('f3').value,p=+document.getElementById('f4').value,yrs=+document.getElementById('f5').value,inc=+document.getElementById('f6').value/100;const yr1=t+r+b+p;let total=0;for(let i=0;i<yrs;i++)total+=yr1*Math.pow(1+inc,i);const yrN=yr1*Math.pow(1+inc,yrs-1),loan_pmt=total*0.006;document.getElementById('r1').textContent='$'+total.toFixed(0);document.getElementById('r2').textContent='$'+yr1.toFixed(0);document.getElementById('r3').textContent='$'+yrN.toFixed(0);document.getElementById('r4').textContent='$'+loan_pmt.toFixed(0)+'/mo';document.getElementById('resultBox').classList.add('show');}</script>"),

("tax-bracket-calculator.html","Tax Bracket Calculator","Find which tax bracket your income falls into. Calculate marginal vs effective tax rate for 2025.","tax bracket calculator, what tax bracket am I in, marginal tax rate, income tax brackets 2025, effective tax rate","&#128179;","#b71c1c","#c62828","finance","&#128176;","Finance",
"""<div class='calc-box'><h2 class='calc-title'>Tax Bracket Calculator 2025 (US)</h2><div class='row g-3'><div class='col-md-6'><label class='form-label'>Taxable Income ($)</label><input type='number' class='form-control' id='f1' value='75000' step='1000'></div><div class='col-md-6'><label class='form-label'>Filing Status</label><select class='form-select' id='f2'><option value='single'>Single</option><option value='married'>Married Filing Jointly</option></select></div></div><button class='btn-calculate mt-4' onclick='calc()'><i class='bi bi-calculator me-2'></i>Calculate</button><div class='result-box' id='resultBox'><div id='tbResults' style='font-size:0.9rem'></div></div></div>""",
"<script>const brackets={single:[[11600,0.10],[47150,0.12],[100525,0.22],[191950,0.24],[243725,0.32],[609350,0.35],[Infinity,0.37]],married:[[23200,0.10],[94300,0.12],[201050,0.22],[383900,0.24],[487450,0.32],[731200,0.35],[Infinity,0.37]]};function calc(){const inc=+document.getElementById('f1').value,st=document.getElementById('f2').value;const br=brackets[st];let tax=0,prev=0,marginal=0,rows='';for(const[lim,rate]of br){const top=Math.min(inc,lim);if(top<=prev)break;const chunk=top-prev,t=chunk*rate;tax+=t;marginal=rate;rows+='<div style=\"display:flex;justify-content:space-between;padding:5px 0;border-bottom:1px solid var(--border)\"><span>'+(prev+1).toLocaleString()+' - '+(lim===Infinity?'&#8734;':lim.toLocaleString())+' @ '+(rate*100)+'%</span><strong>$'+t.toFixed(0)+'</strong></div>';prev=lim;}rows='<div style=\"margin-bottom:8px\"><strong>Total Tax: $'+tax.toFixed(0)+'</strong> | Marginal: '+(marginal*100)+'% | Effective: '+(tax/inc*100).toFixed(1)+'%</div>'+rows;document.getElementById('tbResults').innerHTML=rows;document.getElementById('resultBox').classList.add('show');}</script>"),

("number-system-calculator.html","Number System Converter","Convert and perform arithmetic in binary, octal, decimal, and hexadecimal number systems.","number system converter, binary arithmetic, hex calculator, binary to decimal, octal to decimal, hex to binary","&#128290;","#4a148c","#6a1b9a","math","&#128290;","Math",
cb("Number System Calculator","<div class='row g-3'><div class='col-md-6'><label class='form-label'>Number 1</label><input type='text' class='form-control' id='f1' value='255' placeholder='Enter number'></div><div class='col-md-6'><label class='form-label'>Base of Number 1</label><select class='form-select' id='b1'><option value='10' selected>Decimal (10)</option><option value='2'>Binary (2)</option><option value='8'>Octal (8)</option><option value='16'>Hex (16)</option></select></div></div>",
[("Decimal","r1"),("Binary","r2"),("Octal","r3"),("Hexadecimal","r4")],"Convert"),
"<script>function calc(){const n=document.getElementById('f1').value.trim().toUpperCase(),b=+document.getElementById('b1').value;let d;try{d=parseInt(n,b);}catch(e){return;}if(isNaN(d))return alert('Invalid input');document.getElementById('r1').textContent=d.toString(10);document.getElementById('r2').textContent=d.toString(2);document.getElementById('r3').textContent=d.toString(8);document.getElementById('r4').textContent=d.toString(16).toUpperCase();document.getElementById('resultBox').classList.add('show');}</script>"),
]

for c in calcs:
    page(*c)

print("\n=== Batch 5 complete! ===")
