import os, re

BASE = r"d:\Datomate AI Lab\CalcWebsite"

# All calculators with metadata (name, url, icon-as-HTML-entity, category, desc, badge)
CALCULATORS = [
  # Finance (hot/top)
  ("EMI Calculator","emi-calculator.html","&#127968;","Finance","Calculate loan EMI instantly","hot"),
  ("GST Calculator","gst-calculator.html","&#128202;","Finance","Add or remove GST from amount","hot"),
  ("SIP Calculator","sip-calculator.html","&#128200;","Finance","Mutual fund SIP returns","top"),
  ("Income Tax Calculator","income-tax-calculator.html","&#129534;","Finance","Calculate income tax 2025","hot"),
  ("Compound Interest Calculator","compound-interest-calculator.html","&#128185;","Finance","CI with different frequencies","top"),
  ("FD Calculator","fd-calculator.html","&#127963;","Finance","Fixed deposit maturity amount",""),
  ("RD Calculator","rd-calculator.html","&#128179;","Finance","Recurring deposit calculator",""),
  ("PPF Calculator","ppf-calculator.html","&#128274;","Finance","Public provident fund returns",""),
  ("HRA Calculator","hra-calculator.html","&#127968;","Finance","House rent allowance exemption",""),
  ("Gratuity Calculator","gratuity-calculator.html","&#127873;","Finance","Employee gratuity amount",""),
  ("NPS Calculator","nps-calculator.html","&#128116;","Finance","National pension scheme returns",""),
  ("Simple Interest Calculator","simple-interest-calculator.html","&#128200;","Finance","Simple interest calculation",""),
  ("Salary Calculator","salary-calculator.html","&#128188;","Finance","CTC to in-hand salary","top"),
  ("Loan Eligibility Calculator","loan-eligibility-calculator.html","&#9989;","Finance","Check how much loan you can get",""),
  ("Car Loan Calculator","car-loan-calculator.html","&#128663;","Finance","Auto loan EMI calculator",""),
  ("Home Loan Calculator","home-loan-calculator.html","&#127969;","Finance","Home mortgage EMI and interest",""),
  ("Retirement Calculator","retirement-calculator.html","&#127796;","Finance","Plan your retirement corpus",""),
  ("Discount Calculator","discount-calculator.html","&#127991;","Finance","Calculate sale price and savings","hot"),
  ("Profit Loss Calculator","profit-loss-calculator.html","&#128176;","Finance","Business profit/loss percentage",""),
  ("Break Even Calculator","break-even-calculator.html","&#9878;","Finance","Find break-even point",""),
  ("ROI Calculator","roi-calculator.html","&#128202;","Finance","Return on investment percentage",""),
  ("Inflation Calculator","inflation-calculator.html","&#128200;","Finance","Future value of money",""),
  ("Currency Converter","currency-converter.html","&#128178;","Finance","Live currency exchange rates","new"),
  ("Credit Card Calculator","credit-card-calculator.html","&#128179;","Finance","Credit card interest and payoff",""),
  ("Net Worth Calculator","net-worth-calculator.html","&#128176;","Finance","Assets minus liabilities","new"),
  ("Loan Comparison Calculator","loan-comparison-calculator.html","&#9878;","Finance","Compare two loan offers","new"),
  ("Mutual Fund SIP Calculator","mutual-fund-sip-calculator.html","&#128200;","Finance","SIP returns and target corpus","new"),
  ("Sukanya Samriddhi Calculator","sukanya-samriddhi-calculator.html","&#128103;","Finance","SSY maturity at 8.2% interest","new"),
  ("Tax Calculator 2025","tax-calculator.html","&#127963;","Finance","New vs old regime comparison","hot"),
  ("Solar Panel Calculator","solar-panel-calculator.html","&#9728;","Finance","Solar savings and payback period","new"),
  ("Mortgage Calculator","mortgage-calculator.html","&#127864;","Finance","Global mortgage calculator",""),
  ("Stock Return Calculator","stock-return-calculator.html","&#128202;","Finance","Calculate stock returns and CAGR",""),
  ("Dividend Calculator","dividend-calculator.html","&#128178;","Finance","Dividend income estimator",""),
  ("Capital Gains Calculator","capital-gains-calculator.html","&#127963;","Finance","Short and long term capital gains",""),
  ("Freelancer Rate Calculator","freelancer-rate-calculator.html","&#128187;","Finance","Hourly/project rate estimator",""),
  ("Debt Payoff Calculator","debt-payoff-calculator.html","&#128279;","Finance","Pay off debt strategy planner",""),
  ("Budget Calculator","budget-calculator.html","&#128200;","Finance","Monthly budget planner",""),
  ("Savings Goal Calculator","savings-goal-calculator.html","&#127919;","Finance","How long to reach savings goal",""),
  ("Payroll Calculator","payroll-calculator.html","&#128176;","Finance","Employee payroll and tax",""),
  ("Lease Calculator","lease-calculator.html","&#128179;","Finance","Vehicle lease payment calculator",""),
  ("Margin Calculator","margin-calculator.html","&#128200;","Finance","Gross and net profit margin",""),
  ("Markup Calculator","markup-calculator.html","&#127991;","Finance","Product markup percentage",""),
  ("Investment Calculator","investment-calculator.html","&#128176;","Finance","Future value of investments",""),
  ("Sales Tax Calculator","sales-tax-calculator.html","&#129534;","Finance","Calculate sales tax amount",""),
  ("Compound Savings Calculator","compound-savings-calculator.html","&#128185;","Finance","Savings growth with compounding",""),
  ("Income Tax Estimator","income-tax-estimator.html","&#129534;","Finance","Quick income tax estimate",""),
  ("Retirement Savings Calculator","retirement-savings-calculator.html","&#127796;","Finance","Retirement corpus planner",""),
  ("Currency Exchange Calculator","currency-exchange-calculator.html","&#128178;","Finance","Currency exchange with rates",""),
  ("Bond Yield Calculator","bond-yield-calculator.html","&#128200;","Finance","Bond yield to maturity",""),
  ("Options Profit Calculator","options-profit-calculator.html","&#128202;","Finance","Options trading profit/loss",""),
  ("Depreciation Calculator","depreciation-calculator.html","&#128200;","Finance","Asset depreciation methods",""),
  ("APY Calculator","apy-calculator.html","&#128185;","Finance","Annual percentage yield",""),
  ("Mortgage Points Calculator","mortgage-points-calculator.html","&#127968;","Finance","Is buying mortgage points worth it",""),
  ("Down Payment Calculator","down-payment-calculator.html","&#127968;","Finance","Home down payment and PMI",""),
  ("Tax Bracket Calculator","tax-bracket-calculator.html","&#129534;","Finance","Find your tax bracket",""),
  ("Loan EMI Calculator","loan-emi-calculator.html","&#127968;","Finance","Detailed EMI breakdown",""),
  ("Childbirth Cost Calculator","childbirth-cost-calculator.html","&#128118;","Finance","Hospital delivery cost estimate",""),
  ("College Cost Calculator","college-cost-calculator.html","&#127891;","Finance","Total college cost planner",""),
  ("Customer LTV Calculator","customer-ltv-calculator.html","&#128182;","Finance","Customer lifetime value",""),
  ("Employee Cost Calculator","employee-cost-calculator.html","&#128188;","Finance","Total cost of hiring employee",""),
  ("Invoice Generator Calculator","invoice-generator-calculator.html","&#128203;","Finance","Professional invoice builder","new"),
  ("Rent vs Buy Calculator","rent-vs-buy-calculator.html","&#127968;","Finance","Rent or buy comparison",""),
  ("Food Cost Calculator","food-cost-calculator.html","&#127829;","Finance","Restaurant food cost percentage",""),
  ("Net Pay Calculator","net-pay-calculator.html","&#128176;","Finance","Take-home pay after deductions",""),
  ("Mileage Reimbursement Calculator","mileage-reimbursement-calculator.html","&#128663;","Finance","IRS mileage reimbursement 2025",""),
  ("Gold Calculator","gold-calculator.html","&#128081;","Finance","Gold price and weight calculator",""),
  ("Property Tax Calculator","property-tax-calculator.html","&#127968;","Finance","Annual property tax estimate",""),
  ("Home Affordability Calculator","home-affordability-calculator.html","&#127969;","Finance","How much house can you afford",""),
  ("Net Promoter Score Calculator","net-promoter-score-calculator.html","&#128200;","Finance","NPS survey score calculator",""),
  ("GST India Calculator","gst-india-calculator.html","&#128202;","Finance","India GST with all slabs 2025","hot"),

  # Health & Fitness
  ("BMI Calculator","bmi-calculator.html","&#9878;","Health","Body mass index check","hot"),
  ("BMR Calculator","bmr-calculator.html","&#128293;","Health","Basal metabolic rate",""),
  ("Calorie Calculator","calorie-calculator.html","&#127822;","Health","Daily calorie needs TDEE","top"),
  ("Ideal Weight Calculator","ideal-weight-calculator.html","&#127919;","Health","Your ideal body weight",""),
  ("Body Fat Calculator","body-fat-calculator.html","&#128208;","Health","Estimate body fat percentage",""),
  ("Protein Calculator","protein-calculator.html","&#129385;","Health","Daily protein intake needs",""),
  ("Water Intake Calculator","water-intake-calculator.html","&#128167;","Health","Daily water requirements",""),
  ("Pregnancy Calculator","pregnancy-calculator.html","&#129354;","Health","Due date and week tracker","top"),
  ("Ovulation Calculator","ovulation-calculator.html","&#128197;","Health","Fertile window calculator",""),
  ("Heart Rate Calculator","heart-rate-calculator.html","&#10084;","Health","Target heart rate zones",""),
  ("Running Pace Calculator","running-pace-calculator.html","&#127939;","Health","Running pace and finish time",""),
  ("Macro Calculator","macro-calculator.html","&#129367;","Health","Protein/carbs/fat ratio",""),
  ("Sleep Calculator","sleep-calculator.html","&#128564;","Health","Best sleep and wake time cycles",""),
  ("One Rep Max Calculator","one-rep-max-calculator.html","&#127947;","Health","Gym 1RM strength estimator",""),
  ("Waist Hip Ratio Calculator","waist-hip-ratio-calculator.html","&#128208;","Health","Waist to hip ratio health check",""),
  ("Blood Pressure Calculator","blood-pressure-calculator.html","&#129658;","Health","BP category and health risk",""),
  ("Blood Sugar Calculator","blood-sugar-calculator.html","&#128200;","Health","Blood glucose level guide",""),
  ("Alcohol Unit Calculator","alcohol-unit-calculator.html","&#127866;","Health","Alcohol units in drinks",""),
  ("Step Counter Calculator","step-counter-calculator.html","&#128099;","Health","Steps to calories and distance","new"),
  ("Life Expectancy Calculator","life-expectancy-calculator.html","&#128202;","Health","Estimate your life expectancy",""),
  ("VO2 Max Calculator","vo2max-calculator.html","&#129330;","Health","Aerobic fitness level",""),
  ("Calorie Deficit Calculator","calorie-deficit-calculator.html","&#128293;","Health","Weight loss calorie deficit",""),
  ("TDEE Calculator","tdee-calculator.html","&#128293;","Health","Total daily energy expenditure",""),
  ("Baby Weight Calculator","baby-weight-calculator.html","&#128118;","Health","Baby weight percentile",""),
  ("BMI Kids Calculator","bmi-calculator-kids.html","&#129303;","Health","BMI for children and teens",""),
  ("BMI Prime Calculator","bmi-prime-calculator.html","&#9878;","Health","BMI prime ratio calculator",""),
  ("Body Surface Area Calculator","body-surface-area-calculator.html","&#129315;","Health","BSA for medication dosing",""),
  ("Lean Body Mass Calculator","lean-body-mass-calculator.html","&#127947;","Health","Lean mass and fat free mass",""),
  ("Army Body Fat Calculator","army-body-fat-calculator.html","&#127947;","Health","US Army body fat standard",""),
  ("Macronutrient Calculator","macronutrient-calculator.html","&#129367;","Health","Detailed macros breakdown",""),
  ("Menstrual Cycle Calculator","menstrual-cycle-calculator.html","&#128197;","Health","Period and cycle tracker",""),
  ("Sleep Cycle Calculator","sleep-cycle-calculator.html","&#128564;","Health","REM sleep cycle planner",""),
  ("Vitamin Calculator","vitamin-calculator.html","&#128138;","Health","Daily vitamin requirements",""),
  ("Hydration Calculator","hydration-calculator.html","&#128167;","Health","Workout hydration needs",""),
  ("BAC Calculator","bac-calculator.html","&#127866;","Health","Blood alcohol content",""),
  ("Due Date Calculator","due-date-calculator.html","&#128118;","Health","Pregnancy due date from LMP",""),
  ("Target Heart Rate Calculator","target-heart-rate-calculator.html","&#10084;","Health","Fat burn and cardio zones",""),
  ("Waist to Height Ratio","waist-to-height-ratio.html","&#128208;","Health","Cardiovascular risk assessment",""),
  ("Body Adiposity Index","body-adiposity-index.html","&#9878;","Health","Alternative to BMI calculator",""),
  ("Creatinine Clearance","creatinine-clearance-calculator.html","&#129658;","Health","eGFR kidney function test",""),
  ("Dose Calculator","dose-calculator.html","&#128138;","Health","Medication dose by weight",""),
  ("Tip Percentage Calculator","tip-percentage-calculator.html","&#128176;","Health","Restaurant tip calculator",""),
  ("Swimming Calorie Calculator","swimming-calorie-calculator.html","&#127940;","Health","Calories burned swimming",""),
  ("Cycling Calorie Calculator","cycling-calorie-calculator.html","&#128690;","Health","Calories burned cycling",""),
  ("Walking Calorie Calculator","walking-calorie-calculator.html","&#128099;","Health","Calories burned walking",""),
  ("Yoga Calorie Calculator","yoga-calorie-calculator.html","&#129340;","Health","Calories burned doing yoga",""),
  ("Body Fat Percentage Calculator","body-fat-percentage-calculator.html","&#128208;","Health","Accurate body fat estimate",""),
  ("Pace Converter Calculator","pace-converter-calculator.html","&#127939;","Health","Running pace unit converter",""),
  ("Wind Chill Calculator","wind-chill-calculator.html","&#127754;","Health","Feels-like temperature",""),

  # Math & Science
  ("Percentage Calculator","percentage-calculator.html","&#128290;","Math","All types of percentage calculations","hot"),
  ("Age Calculator","age-calculator.html","&#127874;","Math","Exact age in years/months/days","hot"),
  ("Scientific Calculator","scientific-calculator.html","&#129518;","Math","Full scientific calculator","top"),
  ("Fraction Calculator","fraction-calculator.html","&#189;","Math","Add subtract multiply fractions",""),
  ("Square Root Calculator","square-root-calculator.html","&#8730;","Math","Square and cube root finder",""),
  ("Exponent Calculator","exponent-calculator.html","&#120143;","Math","Power and exponent calculator",""),
  ("LCM GCD Calculator","lcm-gcd-calculator.html","&#128208;","Math","Least common multiple and GCD",""),
  ("Average Calculator","average-calculator.html","&#128290;","Math","Mean median mode calculator",""),
  ("Statistics Calculator","statistics-calculator.html","&#128202;","Math","Full stats analysis tool",""),
  ("Quadratic Calculator","quadratic-calculator.html","&#120143;","Math","Quadratic equation solver",""),
  ("Trigonometry Calculator","trigonometry-calculator.html","&#128210;","Math","Sin cos tan calculator",""),
  ("Matrix Calculator","matrix-calculator.html","&#128208;","Math","Matrix operations solver",""),
  ("Logarithm Calculator","logarithm-calculator.html","&#128290;","Math","Log and natural log calculator",""),
  ("Factorial Calculator","factorial-calculator.html","&#128290;","Math","Factorial and permutations",""),
  ("Prime Number Calculator","prime-number-calculator.html","&#128290;","Math","Check if a number is prime",""),
  ("Random Number Generator","random-number-generator.html","&#127922;","Math","Generate random numbers",""),
  ("Binary Calculator","binary-calculator.html","&#128187;","Math","Binary/hex/octal converter",""),
  ("Standard Deviation Calculator","standard-deviation-calculator.html","&#128202;","Math","Population and sample SD",""),
  ("Half Life Calculator","half-life-calculator.html","&#9762;","Math","Radioactive half-life decay",""),
  ("Molarity Calculator","molarity-calculator.html","&#9879;","Math","Solution concentration moles",""),
  ("Density Calculator","density-calculator.html","&#128208;","Math","Mass volume density formula",""),
  ("Acceleration Calculator","acceleration-calculator.html","&#127939;","Math","Newton motion equations",""),
  ("Kinetic Energy Calculator","kinetic-energy-calculator.html","&#9889;","Math","Kinetic energy from mass speed",""),
  ("Ohms Law Calculator","ohms-law-calculator.html","&#9889;","Math","Voltage current resistance",""),
  ("Ohms Law Advanced","ohms-law-advanced-calculator.html","&#9889;","Math","Advanced circuit calculations",""),
  ("pH Calculator","ph-calculator.html","&#9879;","Math","Acid base pH level",""),
  ("Wavelength Frequency Calculator","wavelength-frequency-calculator.html","&#127754;","Math","Wave physics calculator",""),
  ("Number Base Converter","number-base-converter.html","&#128187;","Math","Binary decimal hex octal",""),
  ("Roman Numeral Converter","roman-numeral-converter.html","&#128210;","Math","Roman numerals converter",""),
  ("Number to Words Converter","number-to-words-converter.html","&#128290;","Math","Numbers spelled in words",""),
  ("Number System Calculator","number-system-calculator.html","&#128187;","Math","Multi-base number system",""),
  ("Specific Gravity Calculator","specific-gravity-calculator.html","&#9879;","Math","Density and API gravity",""),
  ("Z-Score Calculator","z-score-calculator.html","&#128202;","Math","Normal distribution z-score",""),
  ("Pipe Flow Calculator","pipe-flow-calculator.html","&#128200;","Math","Fluid flow rate and pressure",""),

  # Unit Converters
  ("Unit Converter","unit-converter.html","&#128208;","Convert","All units in one place","hot"),
  ("Length Converter","length-converter.html","&#128208;","Convert","Meters feet inches miles",""),
  ("Weight Converter","weight-converter.html","&#9878;","Convert","Kg pounds stone converter",""),
  ("Temperature Converter","temperature-converter.html","&#127777;","Convert","Celsius Fahrenheit Kelvin","top"),
  ("Speed Converter","speed-converter.html","&#128663;","Convert","Km/h mph m/s converter",""),
  ("Volume Calculator","volume-calculator.html","&#128208;","Convert","Volume of any 3D shape",""),
  ("Area Calculator","area-calculator.html","&#128208;","Convert","Area of any 2D shape",""),
  ("Pressure Converter","pressure-converter.html","&#127754;","Convert","PSI bar pascal converter",""),
  ("Energy Converter","energy-converter.html","&#9889;","Convert","Joules calories kWh converter",""),
  ("Data Converter","data-converter.html","&#128187;","Convert","Bytes KB MB GB TB converter",""),
  ("Digital Storage Converter","digital-storage-converter.html","&#128187;","Convert","Digital storage units",""),
  ("Time Unit Converter","time-unit-converter.html","&#128336;","Convert","Seconds minutes hours days",""),
  ("Angle Converter","angle-converter.html","&#128208;","Convert","Degrees radians gradians",""),
  ("Speed Distance Time Calculator","speed-distance-time-calculator.html","&#128663;","Convert","Speed distance time formula",""),
  ("Force Converter","force-converter.html","&#9889;","Convert","Newton pound-force converter",""),
  ("Power Unit Converter","power-unit-converter.html","&#9889;","Convert","Watts HP BTU converter",""),
  ("Cooking Converter","cooking-converter.html","&#127859;","Convert","Cups tablespoons ml oz",""),
  ("Currency Inflation Calculator","currency-inflation-calculator.html","&#128178;","Convert","Inflation adjusted value",""),

  # Date & Time
  ("Date Calculator","date-calculator.html","&#128197;","DateTime","Days between two dates","hot"),
  ("Age Difference Calculator","age-difference-calculator.html","&#127874;","DateTime","Age gap between two people",""),
  ("Add Days Calculator","add-days-calculator.html","&#128197;","DateTime","Add or subtract days from date",""),
  ("Days Until Calculator","days-until-calculator.html","&#128197;","DateTime","How many days until event",""),
  ("Working Days Calculator","working-days-calculator.html","&#128197;","DateTime","Business days between dates",""),
  ("Time Between Dates Calculator","time-between-dates-calculator.html","&#128336;","DateTime","Exact time gap calculator",""),
  ("Time Zone Converter","time-zone-converter.html","&#127760;","DateTime","World clock converter",""),
  ("Countdown Calculator","countdown-calculator.html","&#128197;","DateTime","Countdown to any event",""),
  ("Anniversary Calculator","anniversary-calculator.html","&#128140;","DateTime","Next anniversary date finder",""),
  ("Week Number Calculator","week-number-calculator.html","&#128197;","DateTime","What week of year is it",""),
  ("Birth Year Calculator","birth-year-calculator.html","&#127874;","DateTime","Year of birth from age",""),
  ("Age on Planet Calculator","age-on-planet-calculator.html","&#127988;","DateTime","Your age on other planets",""),
  ("Pet Age Calculator","pet-age-calculator.html","&#128049;","DateTime","Dog and cat age in human years",""),

  # Education
  ("Grade Calculator","grade-calculator.html","&#127891;","Education","Final grade calculator","hot"),
  ("GPA Calculator","gpa-calculator.html","&#127891;","Education","Semester and cumulative GPA","top"),
  ("Percentage Calculator","percentage-off-calculator.html","&#128290;","Education","Percentage off and increase",""),
  ("CGPA to Percentage","cgpa-to-percentage-calculator.html","&#127891;","Education","CGPA to marks percentage",""),
  ("GPA to Percentage","gpa-to-percentage.html","&#127891;","Education","GPA to percentage conversion",""),
  ("GPA College Calculator","gpa-calculator-college.html","&#127891;","Education","US college GPA calculator",""),
  ("Exam Score Calculator","exam-score-calculator.html","&#128221;","Education","Exam marks percentage",""),
  ("Study Hours Calculator","study-hours-calculator.html","&#128218;","Education","Study time planner",""),
  ("Reading Time Calculator","reading-time-calculator.html","&#128218;","Education","How long to read a book",""),
  ("Word Count Calculator","word-count-calculator.html","&#128221;","Education","Words characters pages",""),
  ("Percentage Change Calculator","percentage-change-calculator.html","&#128290;","Education","Increase decrease percentage",""),

  # Construction & Home
  ("Square Footage Calculator","square-footage-calculator.html","&#127968;","Home","Room and floor sq ft","hot"),
  ("Tile Calculator","tile-calculator.html","&#127968;","Home","Tiles needed for floor/wall",""),
  ("Paint Calculator","paint-calculator.html","&#127912;","Home","Paint needed for room",""),
  ("Concrete Calculator","concrete-calculator.html","&#127959;","Home","Concrete volume and bags",""),
  ("Brick Wall Calculator","brick-wall-calculator.html","&#127959;","Home","Bricks needed for wall",""),
  ("Flooring Calculator","flooring-calculator.html","&#127968;","Home","Flooring material quantity",""),
  ("Roof Pitch Calculator","roof-pitch-calculator.html","&#127968;","Home","Roof angle and slope",""),
  ("Stair Calculator","stair-calculator.html","&#127968;","Home","Stair rise run dimensions",""),
  ("Fence Calculator","fence-calculator.html","&#127968;","Home","Fencing material estimate",""),
  ("Mulch Calculator","mulch-calculator.html","&#127807;","Home","Garden mulch quantity",""),
  ("Gravel Calculator","gravel-calculator.html","&#127959;","Home","Gravel and stone estimate",""),
  ("Drywall Calculator","drywall-calculator.html","&#127968;","Home","Drywall sheets needed",""),
  ("Concrete Volume Calculator","concrete-volume-calculator.html","&#127959;","Home","Concrete pour calculator",""),
  ("Aspect Ratio Calculator","aspect-ratio-calculator.html","&#128208;","Home","Screen aspect ratio",""),
  ("Land Area Calculator","land-area-calculator.html","&#127968;","Home","Land area in acres and sqft",""),
  ("Paint Coverage Calculator","paint-coverage-calculator.html","&#127912;","Home","Paint gallons coverage",""),
  ("Paint Cost Calculator","paint-cost-calculator.html","&#127912;","Home","Total painting project cost",""),
  ("Electricity Usage Calculator","electricity-usage-calculator.html","&#9889;","Home","Appliance power consumption",""),
  ("Electricity Bill Calculator","electricity-bill-calculator.html","&#9889;","Home","Monthly electricity cost",""),
  ("Electricity Unit Calculator","electricity-unit-calculator.html","&#9889;","Home","kWh unit calculation",""),
  ("Electricity Saving Calculator","electricity-saving-calculator.html","&#9889;","Home","LED and appliance savings",""),
  ("Solar Power Calculator","solar-power-calculator.html","&#9728;","Home","Solar panel output kWh",""),
  ("Solar Savings Calculator","solar-savings-calculator.html","&#9728;","Home","Solar panel ROI and payback",""),

  # Tech & Digital
  ("Random Password Generator","random-password-generator.html","&#128274;","Tech","Secure password creator","hot"),
  ("IP Subnet Calculator","ip-subnet-calculator.html","&#127760;","Tech","Network subnet mask calculator",""),
  ("Bandwidth Calculator","bandwidth-calculator.html","&#128187;","Tech","Network bandwidth estimator",""),
  ("Download Time Calculator","download-time-calculator.html","&#128190;","Tech","File download time estimator",""),
  ("Color Code Converter","color-code-converter.html","&#127912;","Tech","HEX RGB HSL color codes",""),
  ("Pixel Density Calculator","pixel-density-calculator.html","&#128248;","Tech","Screen PPI and DPI",""),
  ("Aspect Ratio Calculator (Screen)","aspect-ratio-calculator.html","&#128249;","Tech","Monitor aspect ratio",""),
  ("Hash Value Calculator","hash-value-calculator.html","&#128274;","Tech","MD5 SHA hash generator",""),

  # Travel & Fuel
  ("Fuel Cost Calculator","fuel-cost-calculator.html","&#9981;","Travel","Road trip fuel cost","hot"),
  ("Fuel Efficiency Calculator","fuel-efficiency-calculator.html","&#128663;","Travel","MPG and km/L converter",""),
  ("Flight Time Calculator","flight-time-calculator.html","&#9992;","Travel","Flight hours and distance",""),
  ("Travel Budget Calculator","travel-budget-calculator.html","&#9992;","Travel","Trip cost planner",""),
  ("Carbon Footprint Calculator","carbon-footprint-calculator.html","&#127807;","Travel","CO2 emissions calculator","new"),
  ("Water Footprint Calculator","water-footprint-calculator.html","&#128167;","Travel","Personal water usage",""),
  ("Horsepower Calculator","horsepower-calculator.html","&#128663;","Travel","Engine horsepower formula",""),
  ("Engine Displacement Calculator","engine-displacement-calculator.html","&#128663;","Travel","Engine CC and displacement",""),
  ("Nautical Mile Calculator","nautical-mile-calculator.html","&#9875;","Travel","Sea distance and knots",""),
  ("Tip Calculator","tip-calculator.html","&#128176;","Travel","Restaurant tip splitter","hot"),
  ("Tip Calculator UK","tip-calculator-uk.html","&#128176;","Travel","UK gratuity calculator",""),
  ("Bill Split Calculator","bill-split-calculator.html","&#128176;","Travel","Split restaurant bill easily",""),

  # Fun & Lifestyle
  ("Love Calculator","love-calculator.html","&#10084;","Fun","Love compatibility percentage","hot"),
  ("Love Compatibility Calculator","love-compatibility-calculator.html","&#10084;","Fun","Zodiac love match score",""),
  ("Lucky Number Calculator","lucky-number-calculator.html","&#127922;","Fun","Numerology lucky number",""),
  ("Name Value Calculator","name-value-calculator.html","&#128290;","Fun","Numerology name value",""),
  ("Zodiac Sign Calculator","zodiac-sign-calculator.html","&#11088;","Fun","Find your zodiac sign",""),
  ("Age on Planet Calculator","age-on-planet-calculator.html","&#127988;","Fun","Your age on Mars Saturn",""),
  ("Random Number Generator","random-number-generator.html","&#127922;","Fun","Generate lucky numbers",""),
  ("Recipe Scaling Calculator","recipe-scaling-calculator.html","&#127859;","Fun","Scale recipe up or down",""),
  ("Horsepower Calculator","horsepower-calculator.html","&#128663;","Fun","Car horsepower estimator",""),
  ("Tide Calculator","tide-calculator.html","&#127754;","Fun","Ocean tide predictor",""),

  # Miscellaneous
  ("Power Consumption Calculator","power-consumption-calculator.html","&#9889;","Other","Device watt-hour cost",""),
  ("Minutes to Hours Calculator","minutes-to-hours-calculator.html","&#128336;","Other","Time conversion calculator",""),
  ("Percentage Off Calculator","percentage-off-calculator.html","&#127991;","Other","Discount amount calculator",""),
  ("Z Score Calculator","z-score-calculator.html","&#128202;","Other","Statistics z-score tool",""),
]

# Build the JS array
lines = ["const ALL_CALCULATORS = ["]
for (name, url, icon, cat, desc, badge) in CALCULATORS:
    badge_part = f', badge: "{badge}"' if badge else ''
    lines.append(f'  {{ name: "{name}", url: "{url}", icon: "{icon}", cat: "{cat}", desc: "{desc}"{badge_part} }},')
lines.append("];")
new_array = "\n".join(lines)

# Read main.js
main_js_path = os.path.join(BASE, "js", "main.js")
with open(main_js_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Replace the ALL_CALCULATORS section
start = content.index("const ALL_CALCULATORS = [")
end = content.index("];", start) + 2
new_content = content[:start] + new_array + content[end:]

with open(main_js_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print(f"Updated ALL_CALCULATORS with {len(CALCULATORS)} calculators")
print(f"main.js size: {len(new_content)} chars")
